// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpga9kxOqNSzLYS57gcVfPbomF9yi8eUo',
    appId: '1:811962132574:web:699a0567861b91e8cb2ccf',
    messagingSenderId: '811962132574',
    projectId: 'sentrypay-ac79b',
    authDomain: 'sentrypay-ac79b.firebaseapp.com',
    storageBucket: 'sentrypay-ac79b.firebasestorage.app',
    measurementId: 'G-BKPVRSB98R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMU55d4Yw1Ble9JIU_oclpIrZlbwkep0',
    appId: '1:811962132574:android:b2fa507ee8edcdd7cb2ccf',
    messagingSenderId: '811962132574',
    projectId: 'sentrypay-ac79b',
    storageBucket: 'sentrypay-ac79b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YkwWjuovLdVdIfiIDGvyZ_J8tjJfUZw',
    appId: '1:811962132574:ios:510187da20bd59d7cb2ccf',
    messagingSenderId: '811962132574',
    projectId: 'sentrypay-ac79b',
    storageBucket: 'sentrypay-ac79b.firebasestorage.app',
    iosBundleId: 'com.example.sentryPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5YkwWjuovLdVdIfiIDGvyZ_J8tjJfUZw',
    appId: '1:811962132574:ios:510187da20bd59d7cb2ccf',
    messagingSenderId: '811962132574',
    projectId: 'sentrypay-ac79b',
    storageBucket: 'sentrypay-ac79b.firebasestorage.app',
    iosBundleId: 'com.example.sentryPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpga9kxOqNSzLYS57gcVfPbomF9yi8eUo',
    appId: '1:811962132574:web:ca27a0d063f9cc4ecb2ccf',
    messagingSenderId: '811962132574',
    projectId: 'sentrypay-ac79b',
    authDomain: 'sentrypay-ac79b.firebaseapp.com',
    storageBucket: 'sentrypay-ac79b.firebasestorage.app',
    measurementId: 'G-CL7FB408B8',
  );
}
